### ISSUE TITLE
Форма заявки на выпуск карты

### ISSUE THREAD

**Issue by amankkg** [IT-Academy-Kyrgyzstan/cs2001-ewallet#51]
**Story** #30 

**Description**
Форма должна включать следующие поля:
- Валюта (KGS)
- Вид карты (VISA, Elcard, MasterCard)

**Comment by Doranbek** [comment]
UserId
OperatorId
Name Card(concat)
Valuta(enum)
CardView(enum)
Status(enum)
Comment
CreatedDate
Decision Date
